name: theortegaproject.github.io - GitHub Pages

on:
  push:
    branches: ["deploy"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Checkout
        uses: actions/checkout@main
      - name: Configure GitHub Pages
        uses: actions/configure-pages@main
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: '.'
      - name: Publish through GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main